apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: application-role-binding
  namespace: application
subjects:
  - kind: ServiceAccount
    name: application-service-account
    namespace: application
roleRef:
  kind: Role
  name: application-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compiler-role-binding
  namespace: compiler
subjects:
  - kind: ServiceAccount
    name: application-service-account
    namespace: application
roleRef:
  kind: Role
  name: compiler-role
  apiGroup: rbac.authorization.k8s.io


