apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: application  
type: Opaque
data:
  access_key: QUtJQVZSVVZVNVU0VjYzT1NZR1Q=
  secret_key: TTZNaUJDbzdHMXZFa3E1aWhxOGhJZEc1YjV2dFRSN0k1NDRlWkdiVQ==
