apiVersion: v1
kind: ServiceAccount
metadata:
  name: compiler-service-account
  namespace: compiler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-service-account
  namespace: application