version: "3"
services:
  backend:
    image: santoshburada/docker_sdk:v1.0
    container_name: docker_sdk-backend-1
    ports:
      - "8080:8000"
    restart: always
    volumes:
      - "upload:/tmp"
    networks:
      - dockersdk
    environment:
      DOCKER_HOST: "tcp://dnd:2375"
      MONGO_URI: "mongodb://user:pass@mongo:27017/"
    env_file:
      - .secrets
    depends_on:
      - dnd
      - mongodb
  dnd:
    image: docker
    container_name: dnd
    restart: always
    entrypoint: dockerd
    command: ["--host=0.0.0.0:2375"]
    privileged: true
    networks:
      - dockersdk
    volumes:
      - "upload:/tmp"
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - dockersdk
    volumes:
      - mongo-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: "user"
        MONGO_INITDB_ROOT_PASSWORD: "pass"
        MONGO_INITDB_DATABASE: "docker_sdk"
    

networks:
  dockersdk:
    name: dockersdk
    ipam:
      driver: default
      
volumes:
  upload:
    name: upload
  mongo-data:
    name: mongo-data
    

